sudo: false
language: python
python:
  -3.5
  -3.6
  -3.7
matrix:
  include:
    - pyhton:3.8
      dist: xenial
      sudo: true
install:
  - pip install poetry
  - portry install -vvv
script:
  - poetry run coverage run --source=httpbin -m pytest -v
  - poetry run coverage report -m
after_success:
  - poetry run coveralls
